### ISSUE TITLE
Czy to dalej działa?

### ISSUE THREAD

**Issue by KartoniarzEssa** [doteq/odrabiamy-bot#1]
Czy ten bot dalej działa? Jeżeli tak to gdzie mogę znaleźć token autoryzacji?

**Comment by doteq** [comment]
Hej, wydaje mi się że nadal powinno bez problemu działać. Aby uzyskać token autoryzacji, musisz wysłać request typu POST na `https://odrabiamy.pl/api/v2/sessions`, a w body musisz wysłać JSON w następującym formacie:
```
{
  "login": "emailtutaj",
  "password": "haslotutaj"
}
```
Jeżeli potrzebujesz z tym pomocy, pisz śmiało.
