### ISSUE TITLE
Autoryzacja

### ISSUE THREAD

**Issue by ryaNNNq** [doteq/odrabiamy-bot#11]
Czym jest "odrabiamyAuth" i co tam trzeba dac

**Comment by m1chaelbarry** [comment]
> Czym jest "odrabiamyAuth" i co tam trzeba dac

https://github.com/doteq/odrabiamy-bot/issues/1#issuecomment-962601416

**Comment by ryaNNNq** [comment]
A mozna prosic o pomoc?

**Comment by ryaNNNq** [comment]
Juz sobie poradzilem, zamykaam
