### ISSUE TITLE
blad POST

### ISSUE THREAD

**Issue by xaveno** [doteq/odrabiamy-bot#13]
przy wysyłaniu requesta POST z podanym w #1 body dostaje to, jest jakiś sposob na to? <!DOCTYPE HTML> <html lang="en-US"> <head> <meta http-equiv="X-UA-Compatible" content="IE=Edge" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <title>Just a moment...</title> <style> html, body {width: 100%; height: 100%; margin: 0; padding: 0;} body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;} h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;} p {font-size: 20px; font-weight: 400; margin: 8px 0;} p, .attribution, {text-align: center;} #spinner {margin: 0 auto 30px auto; display: block;} .attribution {margin-top: 32px;} @keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} } @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} } #cf-bubbles > .bubbles { animation: fader 1.6s infinite;} #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;} #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;} .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; } a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; } a:hover{color: #f4a15d} .attribution{font-size: 16px; line-height: 1.5;} .ray_id{display: block; margin-top: 8px;} #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; } #cf-hcaptcha-container { text-align:center;} #cf-hcaptcha-container iframe { display: inline-block;} </style> <meta http-equiv="refresh" content="35"> <script> //<![CDATA[ (function(){ window._cf_chl_opt={ cvId: "2", cType: "non-interactive", cNounce: "43312", cRay: "7018011859c19c24", cHash: "b943253397e2d16", cUPMDTk: "\/api\/v2\/sessions?__cf_chl_tk=73qqZPW7fUvrEIHP7WYmQoL8scC.B9DhsjPTb.wFZVI-1650899413-0-gaNycGzNByU", cFPWv: "g", cTTimeMs: "1000", cRq: { ru: "aHR0cHM6Ly9vZHJhYmlhbXkucGwvYXBpL3YyL3Nlc3Npb25z", ra: "TW96aWxsYS81LjAgKGNvbXBhdGlibGU7IEdvb2dsZS1BcHBzLVNjcmlwdCk=", rm: "UE9TVA==", d: "x0n2rcICdmfrAWf2FveThh6j2baS2CwEhHrvQ6/pinUPf1W3nUkHmOvpLxuBhMC3du6h3RHpz3vVOOhROh76sswf7SJao/11KXXhgiRYQ2rSts068gnojOOrvDDt0lCWKoQApQljm//6SEv2svT3ur5boxcR4kjrLsluayzvN56NzcFsFPjosd8HxmOSRUtR82ci3rWPjtCQVhWhsB7H5UKSOh5GvhnO1XFJ7Nm+WI0p0d/dPDkUPdsZlO7+qPBc66zuDDLVYfO0hoGFqptmallO/apjWNjrzD9FOHn1YC5a0RUI1nNLN+26lbRt5m93ZRlvTXVZ7lMtvI/BfnVqzHY4fxgmerPQYbCtdoeqtB7YOkNjiwV/Lpxjhe8f1tYT2Q0bVj6QYA8b8RKEmtBeBVJO8l4M7nTpwv4wVn41I7Vs4prd9uulWeDGE6Af6t4wFivqZAStdGarFApn1roaDIcK/Rmy1srnZfdd+E0rQABVLJOL+kB12tycy7m+QZC2hBwP9h5rGY6yOTXEMX+HX6brGeLuRrClWHX/goITTBc1mCHE03HL0mR8O44isrcT", t: "MTY1MDg5OTQxMy44MjEwMDA=", m: "hr54P6xImuZwCem+1Gc0/LLpBpYCwvkeYLcPUGnjgog=", i1: "4Xb9eVrvEVEBbc3OibTMgg==", i2: "Nv1p718dqfHCLi6CuWY4hg==", zh: "sUCC+9IkPjPgDwLL2hmaV/w3hVpBCYFpkBtvpOZPTDA=", uh: "w+b1SJd2gmGBdDFY97HcyPnjNoDqFKSWUp810fKRy6o=", hh: "/D4U0kg6BEqjbEJ7Um6lfci5BVQMST/Acy2R74ezt9g=", } } window._cf_chl_enter = function(){window._cf_chl_opt.p=1}; })(); //]]> </script> </head> <body> <table width="100%" height="100%" cellpadding="20"> <tr> <td align="center" valign="middle"> <div class="cf-browser-verification cf-im-under-attack"> <noscript> <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1> </noscript> <div id="cf-content" style="display:none"> <div id="cf-bubbles"> <div class="bubbles"></div> <div class="bubbles"></div> <div class="bubbles"></div> </div> <h1><span data-translate="checking_browser">Checking your browser before accessing</span> odrabiamy.pl.</h1> <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none"> <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p> </div> <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p> <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p> <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p> </div> <form class="challenge-form" id="challenge-form" action="/api/v2/sessions?__cf_chl_f_tk=73qqZPW7fUvrEIHP7WYmQoL8scC.B9DhsjPTb.wFZVI-1650899413-0-gaNycGzNByU" method="POST" enctype="application/x-www-form-urlencoded"> <input type="hidden" name="md" value="av_ZQmiyRDM8XA010FCYKVRYznr927eq8IWA_dTP0rk-1650899413-0-ATxqNU_2G36LsP3LvC2wZLhzRBvsWyB3tkB9hIHm31J3SgFSNsjh_-BZau__2Ihg6RMWp-37ZmboUocStEcX4Fd0DOQ_9enVUnNDEYTjnhwdpCIaijXujRLDSfSG41xXxuyC5MZyoQ5iGIVyx3WDNI1dmnmhn7u6fBq_ET99nv6HnPD6ssNoek2x9OG6-u1nUx4xOpWfDwRK_R10D6-O82Wl8Foqs1hu2trqZplbUO2dD2jX5MWtkxxL2yOcfIXEgX3W6p2-4TQMJwFZpjUOTvHZPq_M6wH9no5zfcgunsagyuZOwRKmWPH2_SmQWmszN_nMCuswCOKt7V43ZKNjO3n704V6BeAyXfQSTFFhHxY0TecG8IfBVlE-p4qNIojEYPKzhUPDsqi886-AuqyGKHTCqNa5RHge-cAmN2LyMFBYEKaQo-IVyM6oOG10WGYAEEqnLSKdMaEptvmbBpKyJbgbINpoPomtfhl0JLQ0GHH-APMhaq3DuHIWMzTCnswMyuqom9XhOKPapMhrrNusI_SD8mK-IdckUaE7jYC5lTg2mil2Zi_NIYNhm1tdeGy6Oq9EeUlmcg7kiOxPXosiFpvvDgEFMFMWzIrI7iR_unEfl-HyoFknTRzBz3FtTvciZqYIOpmUAGNfQhoO-JRn2wg" /> <input type="hidden" name="r" value="Can5rxOLavcjVTK_v24LVE4bQJWm3hT_iDDGL4EgenU-1650899413-0-AdzoS928VfoG4ePWqliFKcJcRIno/ou3y+AN+FHZ9v6PvZmUlOyMFTf79KT7RVZYbJIynFmDYKoZDvUNC5ZkQ7FS8KXMzndmZbmA4ZZNQU1f02TiLDzlyZ7SZYopF8XYW96Y8xZkruRb0/R0KVVesyppvyG9T9bX2sNSDSaQ4nHrJPNsJXNCWjb3857YpcsuPWlCqFNZ+uJDOBYFW8h9doRxMDvOjBD20NhbeA7HuFReECE5rrQK1AXH4xVDuqU3VwUYADmT7ngzZV6aO7jkfqnOdSPQ5vVssdJKxzpYTnuv89InDL+WqPMymxX9cmCh50bUkaOZR/h7ST3rtH0z9Z6Lugw8XO8rgUtkvacWbcdxNzxt7sc5HREkUGhTD3Yn7gZIpPve5F1AjJy/cw9OyzQ4a4oJNk4XQJ+w5S+IPKXR0CPFZvsbPvCJuIce0wSLCfugXYLMSNPc+YGixc4dFYRCno6i2nrfaYXKGViG3MwqYAolYZrFMpcml6VqzJ7B5CEt8ki25Hj2B0RUd4awQC2GErRNG1JH1/02NQhn77DrwetV5ZfeeMX5Fp2SksRHinR+g3lvv09KPF9eHY6RwrADSgJr+NH7Wu8skGU9JBfvoHac34vbtONXUCVEQFzgTN7q3N1P93oZMJVfxvKhI/3GnIUdl4plOq+j4FyeARs/h0CMY/phJb1XJ3iXQ/2gsaF1VOA4LCMRX0hz86cRE1onXfIflQpvsDNS/Ae1FlkPHa+i873iX07SvNz1fv/lWAtaczUZC8Wej6/lH3PrgFLkMD72aZBAKxWT47gjRlNc49Gx8gflAuTadt95hJ5is7PwCbX19V8y39Q0Y6wYDVjdxfgHwRtc9NTz/H4ouUgpaDqyfuxuW0xo+WWh4qZyaLn1Dr7CRp6bKUBrbgz9Gr42s225rjntaNRoZzHnmczVPKJcUc0orWZUmhesWeaL3pT4QL7sAJP+S+/omVq48y0XtgErYI5bOTFPi2ek5Xg8F16rEHZppZyB+IpbWBpIdj2uL1YGKAIlzN4pGvQSpdEXXymJ4+Fyf6hqBFq3IRcBUO5daoZV2LgJMefEn5x+OGGoFn07r++mxWvS0rzloADJcFvt5H3wMyPU4xQl6NlY3YJeUZFsCObvllZ6Obg7jqNeqSB0VjmCgigOI1eBmtkQ0+i1RiPoIkcjO6G4ZvgqpVtYKihgvYue7oMUte8Qs9NsiclmhLA6DfOjo7jZEHSz+R0OQ7dSqFYgsBu6N46lDgqGK/Vc60zCzYt8BKMzTsv6GS5C2io9dvVkrrTASjOPqsHsxlFbRTQAhQ1ODhr+aWF+ylR8LiQ1NB1PJkgO5XWm9cmBuJIK1rp5xABhdj00eba442foRgxoZurg320s3xlqpkdR3u8QJoiFJnE90dbKzDVz/2PlCIbEctOZHg4/XSSClLl3GDsfMJwwjIm/eBvvfxNRijOY7NCRg5ccoz4LdrKXZQAKOoGdm080S2ewt23vQoNTy0TWeVVT80EFj14Ht6/oKA7LIv1e58wOWG4ABkSDDoQtwmK9pk+8g+W1oykygmD2aduFPW2UoXBVAhNH86hBvA2vfKaj5MQQvFFYzXq0MmKruUexW7otCssCI+FYJvAgSDSxIqTFP5uQTxyRhlYGx3prfhHuvilwEP0v6qoKWS9AsazkMKyVjLZcp82UuxXuKQyjTEqga2jrw90/iA8VL74oMZBFVDq5uoCki4+/8ylqD8ZjAqQC5l1HI0NwcfTzPDjF1lgf9Bd7"/> <input type="hidden" value="02e993b1622ddad691457a87c0cdf649" id="jschl-vc" name="jschl_vc"/>  <input type="hidden" name="pass" value="1650899414.821-69VN6XXriz"/> <input type="hidden" id="jschl-answer" name="jschl_answer"/> </form> <script> //<![CDATA[ (function(){ var a = document.getElementById('cf-content'); a.style.display = 'block'; var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent); var trkjs = isIE ? new Image() : document.createElement('img'); trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=7018011859c19c24"); trkjs.id = "trk_jschal_js"; trkjs.setAttribute("alt", ""); document.body.appendChild(trkjs); var cpo=document.createElement('script'); cpo.type='text/javascript'; cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1?ray=7018011859c19c24"; window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.indexOf('?') !== -1 ? '?' : location.search; window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash; if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) { var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash; history.replaceState(null, null, "\/api\/v2\/sessions?__cf_chl_rt_tk=73qqZPW7fUvrEIHP7WYmQoL8scC.B9DhsjPTb.wFZVI-1650899413-0-gaNycGzNByU" + window._cf_chl_opt.cOgUHash); cpo.onload = function() { history.replaceState(null, null, ogU); }; } document.getElementsByTagName('head')[0].appendChild(cpo); }()); //]]> </script> <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=7018011859c19c24')"> </div> </div> <div class="attribution"> DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> <br /> <span class="ray_id">Ray ID: <code>7018011859c19c24</code></span> </div> </td> </tr> </table> </body> </html>

**Comment by m1chaelbarry** [comment]
musisz coś źle wysyłać bo sprawdziłem przed chwilą i mi działa

**Comment by xaveno** [comment]
A mógłbyś mnie jakoś pokierować jak to zrobić aby było git?

**Comment by m1chaelbarry** [comment]
@xaveno
Osobiście używam thunder clienta - rozszerzenia do VSCode. 

wchodzę w panel rozszerzenia klikając w przycisk po lewej stronie
![panel](https://user-images.githubusercontent.com/69900794/165361203-ad2e4fe4-70cb-484f-a691-fa62cc3fb8b7.png)
następnie w "New Request"
![newrequest](https://user-images.githubusercontent.com/69900794/165361314-61b0019f-c532-4665-b0f7-fc422cebfe71.png)


tu są moje ustawienia
![screen](https://user-images.githubusercontent.com/69900794/165360458-ab56832b-d284-4daa-84f2-aea8d3bc0306.png)

oczywiście zmieniam dane w cudzysłowach
naciskam "Send" i  po prawej dostaje token
![response](https://user-images.githubusercontent.com/69900794/165360949-08d0f052-c58a-45f5-b36d-9296cb4c4597.png)

**Comment by xaveno** [comment]
Dobra dzieki wielkie zaraz spróbuje

**Comment by xaveno** [comment]
dzieki dziala, zamykam
