### ISSUE TITLE
problem z hostowaniem bota

### ISSUE THREAD

**Issue by xaveno** [doteq/odrabiamy-bot#14]
cześć, przy próbie hostowania bota mam taki błąd, nie znam się więc prosiłbym o pomoc.
![image](https://user-images.githubusercontent.com/104170638/165373136-ebe54678-d68f-420a-b0d2-2ab88450a0e6.png)
![image](https://user-images.githubusercontent.com/104170638/165373412-3336d81d-8f5e-427e-9359-9603454d0cdf.png)
hostuje na sparkedhoscie

**Comment by xaveno** [comment]
![ezgif com-gif-maker (18)](https://user-images.githubusercontent.com/104170638/165530494-cf936d2d-f5bf-4243-a456-9950ebb191b8.gif)

**Comment by KartoniarzEssa** [comment]
Widzę że to pterodactyl więć mogę pomóc.
Po pierwsze trzeba pobrać pliki bota i zbudować go komendami które są podane na stronie głównej
![image](https://user-images.githubusercontent.com/81422890/169708666-72130a38-07ff-40a6-a156-2be125fe8f0a.png)


Następnie wrzucić zbudowane pliki przez sftp, pterodactyl ma zakładkę **settings** do tego, są tam adres oraz nazwa użytkownika do połączenia, hasło jest prawdopodobnie takie samo jak do panelu. (Możesz usunąć wszystkie pliki które są na serwerze i wrzucić wszystko z pobranego folderu)

Następnie tam gdzie masz **Variables** w polu **startup file** wpisz **dist/main.js**

Jeśli chodzi o konfigurację to możesz edytować token bota, kanały w pliku **config.js** w katalogu **dist**
![image](https://user-images.githubusercontent.com/81422890/169708643-ed6d006d-c795-4b27-8ee9-72343a7dbcb4.png)

Jeśli będzie jeszcze jakiś problem to możesz pisać na dc
Kartoniarz#9608
