### ISSUE TITLE
Większy rozmiar screenów

### ISSUE THREAD

**Issue by m1chaelbarry** [doteq/odrabiamy-bot#2]
Obecnie zdjęcia przesyłane przez bota są bardzo małe, oraz raczej w jednej długiej linijce tekstu co utrudnia czytanie na discordzie.
Jest możliwość zwiększenia czcionki i może jakiś word-wrap?

**Comment by doteq** [comment]
Rzeczywiście, generowanie zdjęć aktualnie jest bardzo dziwne i ma zrobione jakieś sztuczki, bo puppeteer ma problemy z renderowaniem svg, czego odrabiamy używa do wyświetlania np. działań matematycznych. Mam w planach przepisania całej tej części kodu i przy okazji chcę właśnie zwiększyć czytelność. W tej chwili jedyne co możesz zrobić to otworzyć oryginał na discordzie co powinno być w pełni czytelne - niezbyt wygodne, ale działa.

**Comment by m1chaelbarry** [comment]
https://github.com/doteq/odrabiamy-bot/pull/3
